### ISSUE TITLE
Use dkp environment variable instead of Windows paths for makefile

### ISSUE THREAD

**Issue by hippydave** [Sterophonick/HeartLib#1]
Hi, this library looks nice, gonna try it out when I get around to some gba dev.

I noticed the main makefile uses hardcoded Windows paths for installing to the dkp folders. I'm on mac, so I'd have to change it, unless you feel like updating it to use the environment variables?

Cheers :)

**Comment by Sterophonick** [comment]
Yeah, sure. I'll get around to it when I get the chance.

**Comment by Sterophonick** [comment]
It should work now, sorry I took so long.

**Comment by hippydave** [comment]
> It should work now, sorry I took so long.

No problem, many thanks!
